/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package circelOfFifths;

public class App {

  private String tones = "cdefgab";

  public int[] getFifths(int note){

  }

  public String noteToString(int note){

  }

  public static void main(String[] args) {
  }
}
