/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package circelOfFifths;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void testNoteToString() {
        App classUnderTest = new App();
        assertEquals("C 0", classUnderTest.noteToString(0));
        assertEquals("C#/Db 0", classUnderTest.noteToString(1));
        assertEquals("C#/Db 1", classUnderTest.noteToString(13));
    }
}
