/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package circle.of.fifths;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class NoteTest {
    @Test void testNoteToString() {
        Note n1 = new Note((byte)0);
        assertEquals("(C 0)", n1.toString());
        assertEquals("(C#/Db 0)", new Note((byte)1).toString());
        assertEquals("(C#/Db 1)", new Note((byte)13).toString());
    }
}
