/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package circle.of.fifths;

import org.junit.jupiter.api.Test;
import java.lang.Exception;
import static org.junit.jupiter.api.Assertions.*;

class NoteTest {
    @Test void testNoteToString() {
        Note n1 = new Note((byte)0);
        assertEquals("(C 0)", n1.toString());
        assertEquals("(C#/Db 0)", new Note((byte)1).toString());
        assertEquals("(C#/Db 1)", new Note((byte)1, (byte)1).toString());
        assertEquals("(C#/Db 1)", new Note((byte)13).toString());
    }

    @Test void testNoteEquals() {
        Note n1 = new Note((byte)7);
        Note n2 = new Note((byte)11, (byte) 9);
        assertTrue(n1.equals(new Note((byte)7)));
        assertTrue(n2.equals(new Note((byte)11, (byte) 9)));
    }

    @Test void testException() {
      Exception e1 = assertThrows(IllegalArgumentException.class,() -> new Note((byte)-1));
      assertEquals("note value out of range", e1.getMessage());

      Exception e2 = assertThrows(IllegalArgumentException.class,() -> new Note((byte)-10, (byte) 1));
      assertEquals("note value out of range", e2.getMessage());

      Exception e3 = assertThrows(IllegalArgumentException.class,() -> new Note((byte)1, (byte) -1));
      assertEquals("octave value out of range", e3.getMessage());
    }
}
