name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup-java
      uses: olafurpg/setup-scala@v6

    - name: Build with Gradle
      run: ./gradlew build

    - name: show failed tests
      run : cat /home/runner/work/circleoffifths/circleoffifths/build/reports/tests/test/index.html
