name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout
    - name: Set up JDK
      uses: actions/setup-java

    - name: Build with Gradle
      run: ./gradlew build
